PresentacionAspNetMvc/Controllers/CarritoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual.Entidades;
using TiendaVirtual.LogicaNegocio;

namespace PresentacionAspNetMvc.Controllers
{
    public class CarritoController : Controller
    {
        // GET: Carrito
        public ActionResult Index()
        {
            ICarrito carrito = (ICarrito)HttpContext.Session["carrito"];
            return View(carrito);
        }

        public ActionResult AgregarProducto(int id, int cantidad)
        {
            ILogicaNegocio ln = (ILogicaNegocio)HttpContext.Application["logicaNegocio"];

            ICarrito carrito = (ICarrito)HttpContext.Session["carrito"];

            IProducto producto = ln.BuscarProductoPorId(id);

            ln.AgregarProductoACarrito(producto, cantidad, carrito);

            return RedirectToAction("Index");
        }
        //public ActionResult Prueba()
        //{
        //    RedirectToAction("MFactura", "Factura");
        //}
    }
}

PresentacionAspNetMvc/Controllers/FacturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TiendaVirtual.Entidades;
using TiendaVirtual.LogicaNegocio;


namespace PresentacionAspNetMvc.Controllers
{
    public class FacturaController : Controller
    {
        // GET: Factura

        public ActionResult MFactura()
        {
            
            ICarrito carrito = (ICarrito)HttpContext.Session["carrito"];
            //ILogicaNegocio ln = new LogicaNegocio(); //Si crear nuevo objeto entra en constructor vacio de lineaNegocio y no debe
            ILogicaNegocio ln = (ILogicaNegocio)HttpContext.Application["logicaNegocio"];
            if (carrito.Usuario == null) { return RedirectToAction("Index", "Productos"); } //orde: medoto Controlador }
            IFactura f = ln.FacturarCarrito(carrito);           
            return View("Index", f);
        }
    }
}

PresentacionAspNetMvc/Views/Carrito/Index.cshtml
@model TiendaVirtual.Entidades.Carrito

@{
    ViewBag.Title = "Index";
}

<section id="carrito" class="row">
    <h3>Usuario :  @(Model?.Usuario?.Nick)</h3>
    <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th>Imagen</th>
                <th>Producto</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.LineasFactura)
            {
            <tr>
                <td>
                    <img alt="" class="thumbnail" height="30" width="40" src="~/fotos/@(item.Producto.Id).png" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Producto.Precio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
            </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td></td>
                <td></td>
                <th>Total</th>
                <td>@Html.DisplayFor(Nombrequequieras => Nombrequequieras.Total)</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td>
                    <a href="@Url.Action("MFactura","Factura")">Facturar</a>
                </td>
            </tr>
        </tfoot>
    </table>
</section>